### ISSUE TITLE
Form elements are not revalidated if not touched after a reset

### ISSUE THREAD

**Issue by tony75** [angular/angular.dart#1605] opened 2014-11-24 15:18 UTC
For instance :

```
    <form role="form" name="form" novalidate>
        <input type="text" ng-required="true" ng-model="inputValue">
        <button type="reset">reset</button>
        <button type="submit" ng-click="submit()" ng-disabled="form.invalid">submit</button>
    </form>
```

- The input is required and is firstly invalid. 
- If we fill it, it becomes valid
- Then, we reset the form, the input becomes empty
- The input becames valid while it is not
- We can submit the form while it sould not be allowed

Expected result : when the form is resetted, the validators should be reevaluated and the input should be flagged as invalid

**Comment by matsko** [comment] 2015-01-12 00:35
@tony75 this PR should fix this: https://github.com/angular/angular.dart/pull/1637

Perhaps this may fix the other `reset()` related issue?

**Comment by tony75** [comment] 2015-01-13 08:49
@matsko thanks, your test case seems good :)

**Comment by matsko** [comment] 2015-01-13 17:15
@tony75 awesome. I'm closing this issue for now. Please correct me if the issue is still a problem.

**Closed by matsko** 2015-01-13 17:15 UTC
Labels: api: may-change-behavior, triage, type: bug
