### ISSUE TITLE
Form remains invalid when invalid element is removed by ng-if 

### ISSUE THREAD

**Issue by lassedamgaard** [angular/angular.dart#1545] opened 2014-10-13 08:54 UTC
A form containing a validated element that is wrapped in an ng-if will remain invalid if the validated element is excluded by a change in the ng-if condition while the model value is invalid. 

For instance, consider the following toy example:

```html
<!DOCTYPE html>

<html ng-app>
<body>
<div ng-form>
    <label>Show input
        <input type="checkbox" ng-model="showInput">
    </label>
    <div ng-if="showInput">
        <label>Enter something here...
        <input type="text" ng-required="true" ng-model="inputValue">
        </label>
    </div>
</div>
<script type="application/dart" src="main.dart"></script>
<script type="text/javascript" src="packages/browser/dart.js"></script>
</body>
</html>
```

Steps to reproduce:
1. Toggle the checkbox to show the input field
2. Type something in the input 
3. Verify in devtools that the ng-form div is valid
4. Clear the input field 
5. Verify that form is invalid
6. Toggle the checkbox to remove the input
7. Verify that the form is still invalid

Expected result: Since no validation is defined once the validated element is removed the form should be valid.

**Comment by matsko** [comment] 2015-01-11 23:43
@lassedamgaard I am unable to reproduce the issue in a test. I followed your example, but this is what I was left with: https://github.com/angular/angular.dart/commit/e0fa441eb88c83a4d8894d94a862277e8ebb62c7

Maybe the bug was fixed on the latest master? Can you try to reproduce it in the browser again and glance over the test to see if something is missing?

**Comment by matsko** [comment] 2015-01-11 23:51
Here's the updated commit: https://github.com/matsko/angular.dart/commit/e0fa441eb88c83a4d8894d94a862277e8ebb62c7

**Comment by matsko** [comment] 2015-01-13 18:12
I just tested this out locally. This works as expected ontop of my latest commit.

**Closed by matsko** 2015-01-13 18:12 UTC
Labels: action: WIP, triage, type: bug
